F
======================================================================
FAIL: test_buildings (suite_tests.SuiteTest)
Testing buildings.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stefano/python/FoBiS/src/unittest/python/suite_tests.py", line 45, in test_buildings
    self.assertEquals(num_failures, 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 1 test in 0.014s

FAILED (failures=1)
