{
  "errors": [], 
  "failures": [
    {
      "test": "suite_tests.SuiteTest.test_buildings", 
      "traceback": "Traceback (most recent call last):\n  File \"/home/stefano/python/FoBiS/src/unittest/python/suite_tests.py\", line 45, in test_buildings\n    self.assertEquals(num_failures, 0)\nAssertionError: 1 != 0\n"
    }
  ], 
  "tests-run": 1
}